### ISSUE TITLE
Not sys.maxint

### ISSUE THREAD

**Issue by thecodechef** [mvnural/sublime-indent-respectful-sort#1]
hey just thought you should know that you put maxint when you should have put sys.maxsize
Before:
rootNode = RootNode(lines, args.get("indent","\t"), 0, int(args.get("maxDepth", sys.maxint)) , onlyDepth)

After: 
rootNode = RootNode(lines, args.get("indent","\t"), 0, int(args.get("maxDepth", sys.maxsize)) , onlyDepth)

**Comment by mvnural** [comment]
Thanks for pointing out. Since I'm not very competent in Python, could you let me know what is the difference between two and what kind of potential issues may the existing code have?

**Comment by thecodechef** [comment]
Well im really competent at it either i just was noticing that it wasn't  working and i took a peek under the hood and and took a look at the python standard lib docs and found what was wrong with it.

**Comment by mvnural** [comment]
Could you let me know how exactly it didn't work? No change? Incorrect sorting? Corrupted file?
Also, Which version of Sublime are you using (2 or 3)? 
Did it work after changing it to `sys.maxsize` ?
Also did you check if there were any error messages in the console( you may open the console by pressing `Ctrl + `` or from `Tools -> View Console`)?

**Comment by mvnural** [comment]
OK. Looks like `Sublime 3` didn't recognize `sys.maxint` parameter. It is now fixed with 24fbb281a64903e9608e6ea0d12e601389034528.
